package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/Genialngash/go-mongo-graphql/graph/model"
)

// Deletetodo is the resolver for the deletetodo field.
func (r *mutationResolver) Deletetodo(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Deletetodo - deletetodo"))
}

// GetTodos is the resolver for the getTodos field.
func (r *queryResolver) GetTodos(ctx context.Context) ([]*model.Todo, error) {
	return []*model.Todo{
		{
			ID:         "1",
			DatabaseID: 2,
			Text:       "lsjdls",
			Done:       true,
		},
	}, nil
}
