// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type JobListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID         string `json:"id"`
	DatabaseID int    `json:"databaseId"`
	Text       string `json:"text"`
	Done       bool   `json:"done"`
}

type CreateJobListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type DeleteJobRespone struct {
	DeleteJobID string `json:"deleteJobId"`
}

type UpdateJobListingInput struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	URL         *string `json:"url"`
}
